# Site settings
name: Ryan's Blog
title: Ryan's Blog
email: ryan@rcorre.net
description: > # this means to ignore newlines until "baseurl:"
  In which I talk about programming and whatnot.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.rcorre.net" # the base hostname & protocol for your site
github_username: rcorre


permalink: /:year/:month/:day/:title/
paginate: 10

# Build settings
markdown: kramdown
highlighter: pygments:

# exclusions
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
